
#BOOST_INCLUDE = /media/Work/Dump/boost_1_44_0/installed_libs/include
BOOST_INCLUDE = /usr/local/include

#BOOST_LIB = /media/Work/Dump/boost_1_44_0/installed_libs/lib/

mf: main.cpp dyndis_max_flow.hpp
	g++ -g -I$(BOOST_INCLUDE) main.cpp -o mf


clean:
	rm -f mf *.o
